### ISSUE TITLE
Failed login doesn't reject

### ISSUE THREAD

**Issue by jisenberg** [jens-maus/node-unifi#112]
I'm trying to write a script that pulls event logs. I plan to automate it. I have everything working but I want to make sure there is some error handling so if something goes wrong I can have a log of it. However, when I try to log in with wrong credentials I never get a callback. The code below prints "Good" when the credentials are OK, but doesn't print "Bad" when they are not.

```js
const unifi = require('node-unifi');
const controller = new unifi.Controller({host: 'XXXXXX', port: 443, sslverify: false});
const fs = require('fs');

const workflow = controller.login('XXXXX', 'XXXXX')
.then(result => {
  console.log("Good");
}).catch(err => {
  console.log("Bad");
});
```

**Comment by thib3113** [comment]
I just tryed, and it seems if the connection failed, login never return . 

```
try {
    const ctrl = new unifi.Controller({ host: 'unifi', port: 443, sslverify: false });
    await ctrl.login('XXXX', 'XXX');
} catch (e) {
    console.error('fail');
}

//when login is incorrect, this is never called
console.log('end');
```
