### ISSUE TITLE
Authorized guest 25 second after authorized with external cloud controller

### ISSUE THREAD

**Issue by xseth** [jens-maus/node-unifi#13]
Hi,

When I call authorized guest with my external controller for the guest can access to internet after 25 second. 
It's work faster with local hosted controller

I tryed to send ap mac address for faster authorization but nothing change... 
 
controller.authorizeGuest(site, mac, duration, function(err, data) {
        console.log(err, data);
        }, undefined, undefined, undefined, ap);
});

I don't know if I correct ? I can not find a solution
If I use unifi guest portal its very fast.
 
thanks

**Comment by jens-maus** [comment]
After having released several new versions, is this issue still relevant? Please reopen if it still exists.
