### ISSUE TITLE
Support the new Unifi Protect Software

### ISSUE THREAD

**Issue by the78mole** [jens-maus/node-unifi#19]
Ubiquity released a new piece of hardware, the Cloud Key 2 and also the brand new Unifi Protect, which maybe will replace Unifi Video in the long run.

Are there plans to support Unifi Protect?

**Comment by jens-maus** [comment]
I don't have any plans to support this. The Cloud Key Gen2 works, thought. And in fact this nodejs class is only targetted to interact with a UniFi Controller either in an old Cloud Key, CloudKey Gen2 or UDM Pro, etc.
