### ISSUE TITLE
What need to be enabled on Controller's interface to allow websocket listen

### ISSUE THREAD

**Issue by NebzHB** [jens-maus/node-unifi#196]
Dear,

as everything have been revamped on Unifi side concerning notifications and stuffs, 

i'm not very sure anymore what settings need to be enabled on the Controller's interface to allow the websocket listen to eg client connect/disconnect... sometimes some of my users have issues to receive these events on UDM SE (latest version 7.3.83) but as they changed alot in event/alarm management lately, i'm not very sure... (eg on my system (software controller), all notification are disabled and i receive client connect/disconnect, but one of my users with all notification enabled receive nothing....)

could you clarify exactly what's needed ?

**Comment by jens-maus** [comment]
> as everything have been revamped on Unifi side concerning notifications and stuffs,
> [...]
> could you clarify exactly what's needed ?

Please elaborate in technical terms what exactly has been revamped and what you expect node-unifi to do differently. However, please keep in mind: This is no discussion or support fora here, it is a bug-/enhancement tracker and you have not raised any concrete technical things here...

**Comment by NebzHB** [comment]
Dear
you misread me or i did not explained it correctly.

I'm just asking what does that lib need to be enabled on the latest unifi controler to work. what are the pre-requisites.

**Comment by jens-maus** [comment]
Sorry? But node-unifi just requires nodejs v14+ and here I am using it perfectly with a UDM Pro an Network 7.3.83. However, please note again that this is no support/help fora here but a bug/issue tracker. And if you don't outline an issue / problem here but rather would like to discuss your needs please move over to an appropriate discussion fora.
