### ISSUE TITLE
UDM-Pro Support

### ISSUE THREAD

**Issue by MC-1984** [jens-maus/node-unifi#24]
@jens-maus You mentioned here [https://github.com/iobroker-community-adapters/ioBroker.unifi/issues/28#issuecomment-626114826](url) that you are working on UDM-Pro / Unifi OS Support. Can you share some details on your progress?

**Comment by jens-maus** [comment]
it‘s done, when it‘s done :) So please a bit more patience as my agenda is quite full with a bunch of things. Or buy me a UDM-Pro and support will appear faster :)

**Comment by MC-1984** [comment]
Okay, no pressure! Thanks for answering and for working on it!
