### ISSUE TITLE
Current master branch not available through npm

### ISSUE THREAD

**Issue by RyanGannon** [jens-maus/node-unifi#6]
The changes yesterday have not been applied to npm

**Comment by jens-maus** [comment]
of course not. I first have to integrate some more things before I will publish a new release. Just that stuff is in the master branch doesn't necessarily mean it have to be in line with what npm is providing as a release.

**Comment by RyanGannon** [comment]
I see, fair enough.

**Comment by jens-maus** [comment]
Ok, I just released version 1.2.0 after having integrated my pending changes.
