### ISSUE TITLE
Funktion: getAlarms ... Parameter archived ohne Funktion?

### ISSUE THREAD

**Issue by bauerpower69** [jens-maus/node-unifi#62]
@jens-maus 

Hallo Jens,

Ich verzweifle ... kann es sein, dass in der Funktion getAlarms der Parameter „archived“ 
nicht ausgewertet wird?
Ich habe gefühlt alles versucht um nur die aktuellen Alarme zu bekommen ... leider bekommen ich nur meine 1411 archivierten + 2 neue :-)

Hier ist mein Original-Post (leider ohne Hilfe :-)) https://forum.iobroker.net/post/546561

Herzlichen Dank

Jörg

**Comment by jens-maus** [comment]
Sollte nun mit den aktuellsten Anpassungen erledigt sein.

**Comment by bauerpower69** [comment]
Vielen Dank für Deinen Einsatz und die geniale Integration :-)

Liebe Grüsse
